version: '3.8'

services:
  tts-api:
    build:
      context: .
      args:
        - HF_TOKEN=${HF_TOKEN}
    ports:
      - "8000:8000"
    environment:
      - DEVICE=cuda
      - API_KEY=${API_KEY}
      - VOICE_DIR=/app/voices
      - LLM_PROVIDER=${LLM_PROVIDER:-local}
      - LLM_MODEL=${LLM_MODEL:-Qwen/Qwen2.5-7B-Instruct-AWQ}
      - GROQ_MODEL=${GROQ_MODEL:-llama3-8b-8192}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - STREAM_BY_SENTENCE=${STREAM_BY_SENTENCE:-true}
      - NO_TORCH_COMPILE=1
    volumes:
      - ${VOICE_DIR:-./voices}:/app/voices
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 